[
  ./audio.nix
  ./boot.nix
  ./browser.nix
  ./docker.nix
  ./fonts.nix
  ./git.nix
  ./i18n.nix
  ./input.nix
  ./mounts.nix
  ./network.nix
  ./nix.nix
  ./polkit.nix
  ./ssh.nix
  ./steam.nix
  ./thunar.nix
  ./tmux.nix
  ./user.nix
  ./virt.nix
  ./zsh.nix
  # Display Manager and related
  ./display/i3.nix
  ./display/kde.nix
  ./display/manager.nix
  ./display/nvidia.nix
  # Package collections
  ./pkgs/media.nix
  ./pkgs/utils.nix
]